repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: |
          (?x)(
            ^pkg/export/filter_test.go
          )
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: golangci-lint
      - id: go-mod-tidy
  - repo: https://github.com/pinglin/conventional-pre-commit
    rev: v1.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
