name: Add PR to Project

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  triage:
    uses: instill-ai/.github/.github/workflows/add-label-to-pr.yml@main
    secrets:
      botGitHubToken: ${{ secrets.botGitHubToken }}
