name: Tests

on: [push, pull_request]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go 1.24.2
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - name: Check out code
        uses: actions/checkout@v5

      - name: Download dependencies
        run: go mod download

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.botGithubToken }}
        run: go test -race ./...

      - name: Build
        run: go build -v ./cmd/inst
