name: GoReleaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          # release
          GITHUB_TOKEN: ${{ secrets.botGitHubToken }}
          GORELEASER_CURRENT_TAG: ${{ steps.changelog.outputs.tag-name }}
          # secrets
          INSTILL_OAUTH_CLIENT_ID: ${{ secrets.oauth2ClientId }}
          INSTILL_OAUTH_CLIENT_SECRET: ${{ secrets.oauth2ClientSecret }}
          # config
          INSTILL_OAUTH_ISSUER: ${{ vars.oauth2Issuer }}
          INSTILL_OAUTH_HOSTNAME: ${{ vars.oauth2Hostname }}
          INSTILL_OAUTH_AUDIENCE: ${{ vars.oauth2Audience }}
          INSTILL_OAUTH_CALLBACK_HOST: ${{ vars.oauth2CallbackHost }}
          INSTILL_OAUTH_CALLBACK_PORT: ${{ vars.oauth2CallbackPort }}
