name: Go Releaser

on:
  push:
    tags:
      - "v*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.botGitHubToken }}
          INSTILL_API_HOSTNAME: "api.instill.tech"
          INSTILL_OAUTH_HOSTNAME: "auth.instill.tech"
          INSTILL_OAUTH_AUDIENCE: "https://api.instill.tech"
          INSTILL_OAUTH_ISSUER: "https://auth.instill.tech/"
          INSTILL_OAUTH_CLIENT_ID: ${{ secrets.oauth2ClientId }}
          INSTILL_OAUTH_CLIENT_SECRET: ${{ secrets.oauth2ClientSecret }}
